spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
        group: DEFAULT_GROUP
        # 重要：元数据 version 必须为 stable 或 gray，与 GrayLoadBalancer 筛选逻辑一致
        metadata:
          version: stable
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        namespace: public
        group: DEFAULT_GROUP
